//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3643
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3643.
// 
namespace OnlineFaturaMobileClient.OnlineFaturaServisi {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://192.168.1.124/OnlineFatura/Service1.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetLUSadress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetLUSadress([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string LUSusr, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string LUSpwd) {
            object[] results = this.Invoke("GetLUSadress", new object[] {
                        LUSusr,
                        LUSpwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLUSadress(string LUSusr, string LUSpwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLUSadress", new object[] {
                        LUSusr,
                        LUSpwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetLUSadress(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/TerminalKullaniciKontrol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement TerminalKullaniciKontrol(string SvcUser, string SvcPass, string CASIOSysGetDeviceIDCode, string MSGetDeviceUniqueID, string User, string Pass) {
            object[] results = this.Invoke("TerminalKullaniciKontrol", new object[] {
                        SvcUser,
                        SvcPass,
                        CASIOSysGetDeviceIDCode,
                        MSGetDeviceUniqueID,
                        User,
                        Pass});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTerminalKullaniciKontrol(string SvcUser, string SvcPass, string CASIOSysGetDeviceIDCode, string MSGetDeviceUniqueID, string User, string Pass, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TerminalKullaniciKontrol", new object[] {
                        SvcUser,
                        SvcPass,
                        CASIOSysGetDeviceIDCode,
                        MSGetDeviceUniqueID,
                        User,
                        Pass}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlElement EndTerminalKullaniciKontrol(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AboneBilgi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement AboneBilgi(string SvcUser, string SvcPass, string SayacNo, string GazAboneNo) {
            object[] results = this.Invoke("AboneBilgi", new object[] {
                        SvcUser,
                        SvcPass,
                        SayacNo,
                        GazAboneNo});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAboneBilgi(string SvcUser, string SvcPass, string SayacNo, string GazAboneNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AboneBilgi", new object[] {
                        SvcUser,
                        SvcPass,
                        SayacNo,
                        GazAboneNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlElement EndAboneBilgi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/FaturaKes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement FaturaKes(string SvcUser, string SvcPass, string SayacNo, string GazAboneNo, string Endeks, string TerminalNo, string SicilNo, string PersonelKodu, string Mesaj, string Durum) {
            object[] results = this.Invoke("FaturaKes", new object[] {
                        SvcUser,
                        SvcPass,
                        SayacNo,
                        GazAboneNo,
                        Endeks,
                        TerminalNo,
                        SicilNo,
                        PersonelKodu,
                        Mesaj,
                        Durum});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFaturaKes(string SvcUser, string SvcPass, string SayacNo, string GazAboneNo, string Endeks, string TerminalNo, string SicilNo, string PersonelKodu, string Mesaj, string Durum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FaturaKes", new object[] {
                        SvcUser,
                        SvcPass,
                        SayacNo,
                        GazAboneNo,
                        Endeks,
                        TerminalNo,
                        SicilNo,
                        PersonelKodu,
                        Mesaj,
                        Durum}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlElement EndFaturaKes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/FaturaSureti", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement FaturaSureti(string SvcUser, string SvcPass, string OkunanSayacNo, string GazAboneNo, string FaturaSeri, string FaturaNo) {
            object[] results = this.Invoke("FaturaSureti", new object[] {
                        SvcUser,
                        SvcPass,
                        OkunanSayacNo,
                        GazAboneNo,
                        FaturaSeri,
                        FaturaNo});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFaturaSureti(string SvcUser, string SvcPass, string OkunanSayacNo, string GazAboneNo, string FaturaSeri, string FaturaNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FaturaSureti", new object[] {
                        SvcUser,
                        SvcPass,
                        OkunanSayacNo,
                        GazAboneNo,
                        FaturaSeri,
                        FaturaNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlElement EndFaturaSureti(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/TerminalGPSKonumKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement TerminalGPSKonumKaydet(string SvcUser, string SvcPass, string TerminalNo, string Latitude, string Longitude, string GSMPos, string Zaman) {
            object[] results = this.Invoke("TerminalGPSKonumKaydet", new object[] {
                        SvcUser,
                        SvcPass,
                        TerminalNo,
                        Latitude,
                        Longitude,
                        GSMPos,
                        Zaman});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTerminalGPSKonumKaydet(string SvcUser, string SvcPass, string TerminalNo, string Latitude, string Longitude, string GSMPos, string Zaman, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TerminalGPSKonumKaydet", new object[] {
                        SvcUser,
                        SvcPass,
                        TerminalNo,
                        Latitude,
                        Longitude,
                        GSMPos,
                        Zaman}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlElement EndTerminalGPSKonumKaydet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/HataKodlariniOku", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement HataKodlariniOku(string SvcUser, string SvcPass) {
            object[] results = this.Invoke("HataKodlariniOku", new object[] {
                        SvcUser,
                        SvcPass});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHataKodlariniOku(string SvcUser, string SvcPass, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HataKodlariniOku", new object[] {
                        SvcUser,
                        SvcPass}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlElement EndHataKodlariniOku(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/YetkiliGSMler", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement YetkiliGSMler(string SvcUser, string SvcPass) {
            object[] results = this.Invoke("YetkiliGSMler", new object[] {
                        SvcUser,
                        SvcPass});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginYetkiliGSMler(string SvcUser, string SvcPass, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("YetkiliGSMler", new object[] {
                        SvcUser,
                        SvcPass}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlElement EndYetkiliGSMler(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GSMLogKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement GSMLogKaydet(string SvcUser, string SvcPass, string TerminalNo, string GSMno, string GSMisim, string Mesaj, string Zaman, string Aktif) {
            object[] results = this.Invoke("GSMLogKaydet", new object[] {
                        SvcUser,
                        SvcPass,
                        TerminalNo,
                        GSMno,
                        GSMisim,
                        Mesaj,
                        Zaman,
                        Aktif});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGSMLogKaydet(string SvcUser, string SvcPass, string TerminalNo, string GSMno, string GSMisim, string Mesaj, string Zaman, string Aktif, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GSMLogKaydet", new object[] {
                        SvcUser,
                        SvcPass,
                        TerminalNo,
                        GSMno,
                        GSMisim,
                        Mesaj,
                        Zaman,
                        Aktif}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlElement EndGSMLogKaydet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/OlayLogKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement OlayLogKaydet(string SvcUser, string SvcPass, string TerminalNo, string Olay, string Zaman) {
            object[] results = this.Invoke("OlayLogKaydet", new object[] {
                        SvcUser,
                        SvcPass,
                        TerminalNo,
                        Olay,
                        Zaman});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOlayLogKaydet(string SvcUser, string SvcPass, string TerminalNo, string Olay, string Zaman, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OlayLogKaydet", new object[] {
                        SvcUser,
                        SvcPass,
                        TerminalNo,
                        Olay,
                        Zaman}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlElement EndOlayLogKaydet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlElement)(results[0]));
        }
    }
}
